name: Rails CI

on:
  pull_request:
    branches:
      - "release/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Ruby on Rails Static Analysis
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: development
      BUNDLE_WITHOUT: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Check Ruby Syntax
        run: |
          find app config db lib -name "*.rb" -print0 | \
          xargs -0 -n1 ruby -wc

      - name: Check Rails Autoloading (Zeitwerk)
        run: bundle exec rails zeitwerk:check

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Brakeman
        run: bundle exec brakeman -q

      - name: Precompile Assets
        run: bundle exec rails assets:precompile
